now release can fail

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Automatic Release
+name: Github Release
 
 on:
   pull_request:
@@ -46,7 +46,13 @@ jobs:
         run: |
           gh issue create --title "Release $VERSION already exists" --body "The release for version $VERSION already exists. Please review and take appropriate action."
 
+      - name: Fail if release exists
+        if: env.exists == 'true'
+        run: |
+          echo "Error: Release $VERSION already exists!"
+          exit 1
+
       - name: gh release create
         if: env.exists == 'false' && (env.RELEASE_TYPE == 'final' || env.RELEASE_TYPE == 'post')
         run: |
-          gh release create --draft --generate-notes --title "Release $VERSION" "$VERSION"
+          gh release create --generate-notes --title "Release $VERSION" "$VERSION"
